import type { Metadata } from "next";
import "./globals.css";
// import Scroll from "../components/scroll/Scroll_Suave"; // Importa o componente Scroll
// IMPORT CURSOR
import BolinhaSeguindoMouse from "../components/Cursor/cursor_bolinha";
export const metadata: Metadata = {
  title: "Academia Digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
        />
       {/* <link rel="stylesheet" href="https://unpkg.com/lenis@1.1.14/dist/lenis.css" /> */}
      </head>

      <body>
        <BolinhaSeguindoMouse />
        {/* <Scroll /> */}
        {children}
        {/* <script
          src="https://unpkg.com/lenis@1.1.14/dist/lenis.min.js"
          defer
        ></script> */}
      </body>
    </html>
  );
}
